export const styles = {
  landingDesktop: "landing-desktop",
  heroSection: "hero-section",
  heroSectionTop: "hero-section__top",
  heroSectionBg: "hero-section__bg",
  heroSectionLogoWrap: "hero-section__logo-wrap",
  heroSectionLogo: "hero-section__logo",
  heroSectionMenu: "hero-section__menu",
  heroSectionContent: "hero-section__content",
  heroSectionCopy: "hero-section__copy",
  heroSectionHighlight: "hero-section__highlight",
  heroSectionPhoneWrap: "hero-section__phone-wrap",
  heroSectionPhone: "hero-section__phone",
  chip: "chip",
  chipActive: "chip--active",
  movement: "movement",
  movementCard: "movement__card",
  movementText: "movement__text",
  simplify: "simplify",
  simplifyArt: "simplify__art",
  avatar: "avatar",
  avatarCard: "avatar__card",
  avatarPhone: "avatar__phone",
  app: "app",
  appGrid: "app__grid",
  appLeft: "app__left",
  appMiddle: "app__middle",
  appRight: "app__right",
  newsletter: "newsletter",
  footer: "footer",
} as const;

