import { injectGlobal } from "@emotion/css";
import stylesheet from "./style.css?raw";

injectGlobal(stylesheet);

export const styles = {
  landingDesktop: "landing-desktop",
  heroSection: "hero-section",
  heroSectionTop: "hero-section__top",
  heroSectionBg: "hero-section__bg",
  heroSectionLogoWrap: "hero-section__logo-wrap",
  heroSectionLogo: "hero-section__logo",
  heroSectionMenu: "hero-section__menu",
  heroSectionContent: "hero-section__content",
  heroSectionCopy: "hero-section__copy",
  heroSectionHighlight: "hero-section__highlight",
  heroSectionPhoneWrap: "hero-section__phone-wrap",
  heroSectionPhone: "hero-section__phone",
  chip: "chip",
  chipActive: "chip--active",
  movement: "movement",
  movementCarousel: "movement__carousel",
  movementCarouselTrack: "movement__carousel-track",
  movementCard: "movement__card",
  movementText: "movement__text",
  movementHeading: "movement__heading",
  movementDescription: "movement__description",
  movementMarker: "movement__marker",
  movementMarkerDesktop: "movement__marker-desktop",
  movementMarkerMobile: "movement__marker-mobile",
  movementImage: "movement__image",
  movementPagination: "movement__pagination",
  movementPaginationDot: "movement__pagination-dot",
  movementPaginationDotActive: "movement__pagination-dot--active",
  simplify: "simplify",
  simplifyHeader: "simplify__header",
  simplifyTitle: "simplify__title",
  simplifySubtitle: "simplify__subtitle",
  simplifyTagline: "simplify__tagline",
  simplifyArt: "simplify__art",
  simplifyArtMask: "simplify__art-mask",
  simplifyArtBase: "simplify__art-base",
  simplifyArtOverlay: "simplify__art-overlay",
  simplifyArtOverlaySecondary: "simplify__art-overlay-secondary",
  simplifyArtImage: "simplify__art-image",
  avatar: "avatar",
  avatarCarousel: "avatar__carousel",
  avatarCarouselTrack: "avatar__carousel-track",
  avatarSlide: "avatar__slide",
  avatarCard: "avatar__card",
  avatarPhone: "avatar__phone",
  avatarSlideImageAvatar: "avatar__phone--avatar",
  avatarSlideImageCommunity: "avatar__phone--community",
  avatarSlideImageShop: "avatar__phone--shop",
  avatarPagination: "avatar__pagination",
  avatarPaginationDot: "avatar__pagination-dot",
  avatarPaginationDotActive: "avatar__pagination-dot--active",
  app: "app",
  appCarousel: "app__carousel",
  appCarouselTrack: "app__carousel-track",
  appLeft: "app__left",
  appMiddle: "app__middle",
  appRight: "app__right",
  appHighlightGlow: "app__highlight-glow",
  appRightSlideImage: "app__right-slide-image",
  appButton: "app__button",
  appButtonIcon: "app__button-icon",
  footerArea: "footer-area",
  newsletter: "newsletter",
  newsletterSelect: "newsletter__select",
  newsletterSelectButton: "newsletter__select-button",
  newsletterSelectButtonOpen: "newsletter__select-button--open",
  newsletterSelectButtonHasValue: "newsletter__select-button--has-value",
  newsletterSelectLabel: "newsletter__select-label",
  newsletterSelectIcon: "newsletter__select-icon",
  newsletterSelectOptions: "newsletter__select-options",
  newsletterSelectOption: "newsletter__select-option",
  newsletterSubmitButton: "newsletter__submit-button",
  footer: "footer",
} as const;

